[pytest]
# only the files with prefix `pytest_` would be recognized as pytest test scripts.
python_files = pytest_*.py
strict_markers = true
# set traceback to "short" to prevent the overwhelming tracebacks
tb = short
# Exclude examples in pulled components (useful for local testing)
norecursedirs = .github managed_components
# log related
log_cli = True
log_cli_level = INFO
log_cli_format = %(asctime)s %(levelname)s %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
# junit related
junit_family = xunit1
## log all to `system-out` when case fail
junit_logging = stdout
junit_log_passing_tests = False

addopts = -s --embedded-services esp,idf -p no:idf-ci --suppress-no-test-exit-code

markers =
  # env markers
  runner_esp_box_3: esp-box-3 runner
  runner_esp32_c3_lcdkit: esp32_c3_lcdkit runner
  runner_esp32_p4_box: esp32_p4_box runner
  runner_esp32_p4_function_ev_board: esp32_p4_function_ev_board runner
  runner_esp32_s3_eye: esp32_s3_eye runner
  runner_esp32_s3_lcd_ev_board: esp32_s3_lcd_ev_board runner
  runner_esp32_s3_lcd_ev_board_2: esp32_s3_lcd_ev_board runner
  runner_esp32_s3_usb_otg: esp32_s3_usb_otg runner
  runner_esp_wrover_kit: esp_wrover_kit runner
  runner_m5dial: m5dial runner
  runner_m5stack_core: m5stack_core runner
  runner_m5stack_core_2: m5stack_core_2 runner
  runner_m5stack_core_s3: m5stack_core_s3 runner
  runner_m5stack_core_s3_se: m5stack_core_s3_se runner
  runner_esp32_azure_iot_kit: esp32_azure_iot_kit runner
  runner_esp32_s2_devkitc_1: esp32_s2_devkitc_1 runner
  runner_esp32_s3_devkitc_1_1: esp32_s3_devkitc_1_1 runner
  runner_esp32_s3_korvo_2: esp32_s3_korvo_2 runner
  runner_m5_atom_s3: m5 Atom S3 runner
  runner_esp32_p4_eye: ESP32-P4 EYE runner
